# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cablespaghetti
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: wednesday-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: wednesday-api

custom:
  wsgi:
    app: app.app
  customDomain:
    domainName: wednesday.sandbox.empennage.net
    basePath: ''
    certificateName: '*.sandbox.empennage.net'
    createRoute53Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_2

provider:
  name: aws
  runtime: python3.12
  region: eu-west-1

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  toot:
    handler: app.toot_random_quote
    events:
      - schedule: cron(0 12 ? * WED *)

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-domain-manager
