org: cablespaghetti
app: wednesday-api
service: wednesday-api

custom:
  wsgi:
    app: src/api.app

provider:
  name: aws
  runtime: python3.12
  region: eu-west-2
  stage: prod
  memorySize: 128
  endpointType: REGIONAL

package:
  include:
    - "!./**"
    - "./src/**"
    - "./utils/**"
    - "./wednesday.csv"
  exclude:
    - "**"
  individually: false

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  toot:
    handler: src/toot.toot_random_quote
    events:
      - schedule: cron(0 12 ? * WED *)

plugins:
  - serverless-wsgi
  - serverless-python-requirements
