org: cablespaghetti
app: wednesday-api
service: wednesday-api

custom:
  pythonRequirements:
    dockerizePip: true
    dockerImage: public.ecr.aws/sam/build-python3.12:1.123.0
  wsgi:
    app: src/api.app

provider:
  name: aws
  # Some python depedencies compile code
  # Architecture must match build machine e.g. arm64 for Macs
  architecture: arm64
  runtime: python3.12
  region: eu-west-2
  stage: prod
  memorySize: 128
  endpointType: REGIONAL

package:
  include:
    - "!./**"
    - "./src/**"
    - "./utils/**"
    - "./wednesday.csv"
  exclude:
    - "**"
  individually: false

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  toot:
    handler: src/toot.toot_random_quote
    events:
      - schedule: cron(0 11 ? * WED *)

resources:
  Resources:
    StaticAssets:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: wednesday-api-static-${sls:stage}
  Outputs:
    StaticAssetsBucketName:
      Value: !Ref StaticAssets

plugins:
  - serverless-wsgi
  - serverless-python-requirements
